services:
  flask-backend:
    build: ./flask-backend
    expose:
      - "8000"  # Flask backend runs on port 8000
    environment:
      - FLASK_ENV=production
    volumes:
      - ./flask-backend/logs:/app/logs  # Map container logs dir to host logs dir

  chatbot-frontend:
    build: ./chatbot-frontend
    ports:
      - "80:80"  # Serve the frontend on port 80
    depends_on:
      - flask-backend
